# Generate heatmaps for modules generated by WGCNA
### Jenni Prokkola and Ben Sutherland - 2018-03-30

# Clean space
rm(list=ls())

# Install packages
# install.packages("RColorBrewer")
# install.packages("gplots")
# install.packages("doBy")
# install.packages("data.table")

library(RColorBrewer)
library(gplots)
library(doBy)
library(data.table)

# Set working directory to point to the sfon_wgcna repo
setwd("~/Documents/10_bernatchez/01_sfon_eqtl/sfon_wgcna/")

# Choose sex to analyze
#sex <- "female"
sex <- "male"

##### 1. Import all required files: ####

geneInfo.filename <- paste("04_results/", sex, "_geneInfo_25k.csv", sep = "")

## Import module info
mod.info <- read.csv(file= geneInfo.filename, header=T, dec=".", row.names = 1)
head(mod.info)
str(mod.info)

## Import counts data
Log_cpm_data <- read.csv(file = "03_normalized_data/normalized_output_matrix_log2.csv", header=T, dec="."
                         , row.names = 1)
Log_cpm_data[1:3, 1:10] # view data
dim(Log_cpm_data)

## Import sample metadata
Sampledata <- read.csv(file="00_archive/sfeq_interpretation_v1.csv", header=T)
head(Sampledata)

#### 2 Prepare expression data for heatmap ####

# Reduce size of sample names in columns
colnames(Log_cpm_data) <- gsub(pattern = "_R1", replacement = ""
    , x =  sub(pattern = ".*lib" , replacement = "lib", x = colnames(Log_cpm_data))
  )

head(colnames(Log_cpm_data))

# Combine sample name with info
Sex_info <- data.frame(Lib_id=Sampledata$lib.ID, sex= Sampledata$sex)

## Add Arctic Charr males (M2)
AC_info <- data.frame(Lib_id = names(Log_cpm_data)[105:113], sex = rep("M2", 9)) # Here M2 is to define a diff colour
Sex_info_all <- rbind(Sex_info, AC_info)
head(Sex_info_all) ; tail(Sex_info_all)

## Order the file by sex
Lib_IDs_ordered <- orderBy(~sex, data=Sex_info_all)
head(Lib_IDs_ordered)


## If mismatch between metadata and expression data, remove columns in expression data not in metadata
Log_cpm_data <- Log_cpm_data[, c(Lib_IDs_ordered$Lib_id)] # note this changes the order of the dataframe
str(Log_cpm_data)
dim(Log_cpm_data) # should now be only 113 samples

## Save out rownames to reintroduce after data.table strips them
gene.names <- rownames(Log_cpm_data)

## Make data.table, then order counts data based on sex
setDT(Log_cpm_data) # make as a data.table
setcolorder(Log_cpm_data, as.character(Lib_IDs_ordered$Lib_id)) # fast column reordering of a datatable by reference
Log_cpm_data[1:3,1:3] # note gene names lost

## Make back to dataframe (# Is this necessary?)
Log_cpm_data <- as.data.frame(Log_cpm_data)

## add gene names again
rownames(Log_cpm_data) <- gene.names
Log_cpm_data[1:3,1:3]

## Make a vector of colors based on sex
sex.color <- as.character(Lib_IDs_ordered$sex)
sex.color[which(sex.color=="M")]<-"steelblue4"
sex.color[which(sex.color=="F")]<-"orange"
sex.color[which(sex.color=="M2")]<-"yellow"


##### 3. Generate heatmap from single module ####
# Note: both columns and rows are clustered by Pearson correlation distances

# Choose module to plot
module <- "yellow"
#module <- "ivory"

## Select module to plot 
# (male or female data, change module color)
mod.genes <- row.names(subset(mod.info, moduleColor==module)) # identify genes from the module
length(mod.genes) # See number of genes in the selected module

### Subset the selected genes from counts data
heat_data <- as.matrix(Log_cpm_data[mod.genes,])

### Distances of genes and samples by Pearson correlation
hc_heat_data_row <- hclust(as.dist(1-cor(t(heat_data))), method="average") 
hc_heat_data_col <- hclust(as.dist(1-cor(heat_data)), method="average")


## Set colors for scale:
hmcol <- colorRampPalette(brewer.pal(9, "GnBu"))(100)

### Draw heatmap to pdf
par(mfrow=c(1,1), mar = c(0,4,2,0), cex = 0.6)
filename <- paste("04_results/", sex,"_", module, "_heatmap_allsamples.pdf", sep = "")
pdf(file = filename, width = 6, height = 6)
heatmap.2(heat_data,Rowv = as.dendrogram(hc_heat_data_row), scale="row", 
          Colv = as.dendrogram(hc_heat_data_col),
          col=hmcol, trace="none", labRow=NA,labCol = NA,
          ColSideColors=c(sex.color),
          margins= c(8,5), srtCol = 70,
          cexCol=0.9, key=TRUE, density.info="density", symkey=FALSE, 
          key.par=list(cex.axis=0.8), key.title=NA, keysize=1.2)

dev.off()

##### 4. Generate heatmap for two modules together ####
# Choose two modules to plot
multi.clust1 <- "darkmagenta"
multi.clust2 <- "steelblue"

mod.genes.2 <- row.names(rbind(subset(mod.info, moduleColor==multi.clust1), subset(mod.info, moduleColor==multi.clust2)))
length(mod.genes.2) #how many genes?

### Subset the selected genes from counts data
heat_data<- as.matrix(Log_cpm_data[mod.genes.2,])

### Distances of genes and samples by Pearson correlation
hc_heat_data_row <- hclust(as.dist(1-cor(t(heat_data))), method="average") 
hc_heat_data_col <- hclust(as.dist(1-cor(heat_data)), method="average")

### Draw heatmap to pdf
par(mfrow=c(1,1), mar = c(0,4,2,0), cex = 0.6)
filename <- paste("04_results/", sex,"_", multi.clust1, "_", multi.clust2, "_heatmap_allsamples.pdf", sep = "")
pdf(file=filename, width = 6, height = 6)
heatmap.2(heat_data,Rowv = as.dendrogram(hc_heat_data_row), scale="row", 
          Colv = as.dendrogram(hc_heat_data_col),
          RowSideColors=c(rep("darkmagenta", 61), rep("steelblue", 65)),
          col=hmcol, trace="none", labRow=NA,labCol = NA,
          ColSideColors=c(sex.color),
          margins= c(8,5), srtCol = 70,
          cexCol=0.9, key=TRUE, density.info="density", symkey=FALSE, 
          key.par=list(cex.axis=0.8), key.title=NA, keysize=1.2)

dev.off()

### Draw legend to pdf
pdf(file="Fig5_legend.pdf", width=6, height=3)
plot.new()
	par(lend="square", mar = c(0,4,2,0))
    legend("top", legend = c("Brook Charr Female", "Brook Charr Male",
    "Acrtic Charr Male"), col = c("orange", "steelblue4", "yellow"), lty= 1,
    lwd = 10, cex=0.8, bty="n", horiz=T)
dev.off()
